language: csharp

mono: none
dotnet: 3.1.101

before_install:
    - sudo apt-get install nuget

install:
    - nuget restore homework.sem3/task4/MyNUnit_task4/MyNUnit_task4.sln

script:
    - dotnet build homework.sem3/task4/MyNUnit_task4/MyNUnit_task4.sln
    - dotnet test homework.sem3/task4/MyNUnit_task4/MyNUnit_task4.sln

