language: csharp
solution: homework.sem3/task1/Lazy_sem3.task1/Lazy_sem3.task1.sln

install:
  - nuget restore homework.sem3/task1/Lazy_sem3.task1/Lazy_sem3.task1.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Release homework.sem3/task1/Lazy_sem3.task1/Lazy_sem3.task1.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./TestsOfLazy/bin/Release/TestsOfLazy.dll