language: csharp

mono: none
dotnet: 3.0

before_install:
    - sudo apt-get install nuget

install:
    - nuget restore homework.sem4/homework1/hw1/hw1.sln

script:
    - dotnet build homework.sem4/homework1/hw1/hw1.sln
    - dotnet test homework.sem4/homework1/hw1/hw1.sln

