language: csharp
mono: none
dotnet: 3.0
before_build:
- nuget restore homework.sem3/task2/MyThreadPool/MyThreadPool.sln
build:
- dotnet build homework.sem3/task2/MyThreadPool/MyThreadPool.sln
test_script:
- dotnet test homework.sem3/task2/MyThreadPool/MyThreadPool.sln