image: Visual Studio 2017

before_build:

  - nuget restore hometask3/3.1/StackCalculatorNameSpace/StackCalculatorNameSpace.sln

build:
   project: hometask3/3.1/StackCalculatorNameSpace/StackCalculatorNameSpace.sln


test_script:
  - dotnet test hometask3/3.1/StackCalculatorNameSpace/StackCalculatorNameSpace.sln

