image: Visual Studio 2019 

before_build:
  - nuget restore homework.sem3/task2/MyThreadPool/MyThreadPool.sln
  
build:
   project: homework.sem3/task2/MyThreadPool/MyThreadPool.sln

test_script:
  - dotnet test homework.sem3/task2/MyThreadPool/MyThreadPool.sln



