image: Visual Studio 2017

before_build:
  - nuget restore Proj/hometask2/StackCalculator.sln

build:
   project: Proj/hometask2/StackCalculator.sln
test_script:
  - nunit3-console Proj/hometask2/StackCalculator.sln \
    --result=myresults.xml;format=AppVeyor