image: Visual Studio 2017

before_build:
  - nuget restore hometask2/2.3/StackCalculator/StaclCalculator.sln

build:
   project: hometask2/2.3/StackCalculator/StaclCalculator.sln

test_script:
  - nunit3-console hometask2/2.3/StackCalculator/StaclCalculator.sln \
    --result=myresults.xml;format=AppVeyor