image: Visual Studio 2019 Preview

before_build:
  - nuget restore Tests/TicTacToe_test2/TicTacToe_test2.sln
  
build:
   project: Tests/TicTacToe_test2/TicTacToe_test2.sln

test_script:
  - dotnet test Tests/TicTacToe_test2/TicTacToe_test2.sln


