image: Visual Studio 2017

before_build:
  - nuget restore C:/Users/alnar/source/repos/StackCalculator/StackCalculator.sln

build:
  project:C:/Users/alnar/source/repos/StackCalculator/StackCalculator.sln

test_script:
  - nunit3-console C:/Users/alnar/source/repos/StackCalculator/StackCalculator.sln\
    --result=myresults.xml;format=AppVeyor