image: Visual Studio 2019 

before_build:

  - nuget restore homework.sem3\task5\GUI_task5\GUIforFTP\GUIforFTP.sln
  
build:
   project: homework.sem3\task5\GUI_task5\GUIforFTP\GUIforFTP.sln

test_script:
  - dotnet test homework.sem3\task5\GUI_task5\GUIforFTP\GUIforFTP.sln


