image: Visual Studio 2017

before_build:
  - nuget restore C:/Proj/hometask2/2.3/StackCalculator.sln

build:
  project:C:/Proj/hometask2/2.3/StackCalculator.sln

test_script:
  - nunit3-console C:/Proj/hometask2/2.3/StaclCalculator.sln\
    --result=myresults.xml;format=AppVeyor