image: Visual Studio 2019


before_build:

  - nuget restore hometask6/6.1/FunctionsOfList/FunctionsOfList.sln

build:
   project: hometask6/6.1/FunctionsOfList/FunctionsOfList.sln
test_script:
  - dotnet test hometask6/6.1/FunctionsOfList/FunctionsOfList.sln

